apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-local-storage-kubnode
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-storage
  hostPath:
    path: /srv/data/cassandra
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubnode
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-local-storage-kubnode2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cassandra-local-storage
  hostPath:
    path: /srv/data/cassandra
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubnode2
